### PR TITLE
Calculated z-map time series for all three sessions

### PR DESCRIPTION
**Pull request by JNPauli**
Hello!

Can I now continue with the SVM? Is there anything else left to do before I proceed with the algorithm?

Thanks

Janos

### CODE REVIEW

**Comment by PeerHerholz** [comment]
Hi, 

is there any reason that the z-maps were not computed for sessions 4 & 5?

**Comment by JNPauli** [comment]
Hi,

> Hi,
> 
> is there any reason that the z-maps were not computed for sessions 4 & 5?

in section 5.0 the z-maps are calculated for session 02,03,04. 
01 has already been calculated, so in total we have z-maps for 1-4.

There is no data for session 05, as far as I know.

Best

Janos

**Comment by PeerHerholz** [comment]
Hi,

ok, thanks. Hm, there's a fifth `run` of the `imagery` `task`. Maybe it didn't get uploaded. I'll check tomorrow. 
However, it's definitely part of the outputs on Brainlife.

**Comment by JNPauli** [comment]
> Hi,
> 
> ok, thanks. Hm, there's a fifth `run` of the `imagery` `task`. Maybe it didn't get uploaded. I'll check tomorrow. However, it's definitely part of the outputs on Brainlife.

Hi,

kk. Then just let me know when it is uploaded. 
But you ment to say "fifth session" and not "fifth run", right?

Janos

**Comment by PeerHerholz** [comment]
Hi,

yes, fifth session, sorry. You can also download the files directly from Brainlife.

**Pull request merged**
